const SESSION_ACTION_TYPE = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  LOADING_START: 'LOADING_START',
  LOADING_END: 'LOADING_END',
  SET_ERROR: 'SET_ERROR',
  SET_IDEAS: 'SET_IDEAS',
  SET_SUCCESS_MESSAGE: 'SET_SUCCESS_MESSAGE',
};

export default SESSION_ACTION_TYPE;
